CREATE TABLE IF NOT EXISTS events (
  eventId INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  title TEXT NOT NULL,
  event_date DATE NOT NULL,
  city TEXT NOT NULL,
  state TEXT NOT NULL,
  description NOT NULL,
  organization TEXT,
  link TEXT,
);
